FROM node:24.13.0-alpine3.23
WORKDIR /app

RUN apk add --no-cache postgresql-client curl

COPY package*.json ./
RUN npm install

COPY . .

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]