# Stage 1: Build
FROM node:24.13.0-alpine3.23 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .
RUN npx prisma generate

# Stage 2: Production
FROM node:24.13.0-alpine3.23

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/generated ./src/generated

EXPOSE 3000
CMD ["node", "dist/main.js"]
