name: transcendence

volumes:
  postgres-data:

networks:
  main-network:

services:

  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    networks:
      - main-network

  client:
    build:
      context: ./docker/client
      dockerfile: Dockerfile.prod
    networks:
      - main-network

  postgres:
    image: postgres:18.1-alpine3.23
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"
      - "80:80"
    networks:
      - main-network

  adminer:
    image: adminer:5.4.1-standalone
    ports:
      - "9000:8080"
    restart: always
    networks:
      - main-network
