name: transcendence

volumes:
  postgres-data:

networks:
  main-network:

services:

  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./docker/api:/app # for dev hot-reloading
      - /app/node_modules # to prevent overwriting node_modules with the host's empty folder
    depends_on:
      - postgres
    networks:
      - main-network

  client:
    build:
      context: ./docker/client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./docker/client:/app # for dev hot-reloading
      - /app/node_modules # to prevent overwriting node_modules with the host's empty folder
    networks:
      - main-network

  postgres:
    image: postgres:18.1-alpine3.23
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main-network

  nginx:
    image: nginx:stable-alpine3.23
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/certs:/etc/nginx/ssl/:ro
    networks:
      - main-network

  adminer:
    image: adminer:5.4.1-standalone
    ports:
      - "9000:8080"
    restart: always
    networks:
      - main-network
