volumes:
  client-node-modules:
    name: tr-client-node-modules
  api-node-modules:
    name: tr-api-node-modules
  postgres-data:
    name: tr-postgres-data

networks:
  main:
    name: tr-main

services:

  nginx:
    image: nginx:stable-alpine3.23
    container_name: tr-nginx
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/ssl/:ro
    networks:
      - main

  client:
    image: tr-client:1.0
    container_name: tr-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev # change to 'prod' for production
    ports:
      - "5173:5173" # dev only (for testing using browser)
    env_file: .env
    volumes:
      - ./client:/app # for dev hot-reloading
      - client-node-modules:/app/node_modules # to prevent overwriting node_modules with the host's empty folder
    depends_on:
      - api
    networks:
      - main

  api:
    image: tr-api:1.0
    container_name: tr-api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev # change to 'prod' for production
    ports:
      - "3000:3000" # dev only (for API testing using curl and ThunderClient)
      - "3001:3001" # Prisma Studio
    env_file: .env
    environment:
       - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    volumes:
      - ./api:/app # for dev hot-reloading
      - api-node-modules:/app/node_modules # to prevent overwriting node_modules with the host's empty folder
    depends_on:
      - postgres
    networks:
      - main

  postgres:
    image: postgres:18.1-alpine3.23
    container_name: tr-postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main
