# HTTP to HTTPS redirection
server {
	listen 80;
	server_name localhost;
	return 301 https://$host$request_uri;
}

# HTTPS setup
server {
	listen 443 ssl;
	ssl_certificate /etc/nginx/ssl/nginx.crt;
	ssl_certificate_key /etc/nginx/ssl/nginx.key;
	ssl_protocols TLSv1.2 TLSv1.3;

	# Frontend
	location / {
		proxy_pass http://client:5173;
		proxy_set_header Host $host; # To preserve the original Host header
		# WebSockets support (for HMR)
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}

	# Backend
	location /api/ {
		proxy_pass http://api:3000/; # Trailing slash is to replace "/api" with "/" in the request path (eg. /api/users → /users)
	}
}
