# HTTP to HTTPS redirection
server {
	listen 80;
	server_name DOMAIN_REPLACE;

	return 301 https://$host$request_uri;
}

# HTTPS setup
server {
	listen 443 ssl;
	server_name DOMAIN_REPLACE;

	# SSL
	ssl_certificate /etc/nginx/ssl/nginx.crt;
	ssl_certificate_key /etc/nginx/ssl/nginx.key;
	ssl_protocols TLSv1.2 TLSv1.3;

	# Client (serving static files build in nginx image)
	location / {
		root /usr/share/nginx/html;
		try_files $uri $uri/ /index.html;
	}

	# API
	location /api/ {
		proxy_pass http://api:3000/; # Trailing slash is to replace "/api" with "/" in the request path (eg. /api/users → /users)

		# Preserve original headers
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}

	# WebSockets
	location /socket.io/ {
		proxy_pass http://api:3000/socket.io/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}
}
