### Get all users
GET http://localhost:3001/users

### Get One user
GET http://localhost:3001/users/5

### Create a user (only mandatory fields)
POST http://localhost:3001/users
Content-Type: application/json

{
	"username": "testuser",
	"email": "test@example.com",
	"password": "test123456789"
}

### Create a user with invalid data
POST http://localhost:3001/users
Content-Type: application/json

{
  "email": "test@example.com"
}

### Create a user (all fields)
POST http://localhost:3001/users
Content-Type: application/json

{
	"email": "test@example1.com",
	"password": "12345678",
	"username": "testuser2"
}

### Create a user (missing fields)
POST http://localhost:3001/users
Content-Type: application/json

{
	"email": "test@example.com"
}

### Delete a user
DELETE http://localhost:3001/users/4

### Update a user (only mandatory fields)
PATCH http://localhost:3001/users/17
Content-Type: application/json

{
	"email": "test@example.com",
	"password": "12345678"
}

### Update a user (with invalid email)
PATCH http://localhost:3001/users/17
Content-Type: application/json

{
	"email": "testexample.com",
	"password": "12345678"
}