# nginx/conf.d/default.conf
server {
	listen 80;
	server_name localhost;

	# Frontend
	location / {
		proxy_pass http://frontend:5173;
	}

	# Backend
	location /api/ {
		proxy_pass http://backend:3000;
	}

	# Adminer (fastcgi)
	location /adminer/ {
		return 301 http://$host:$server_port/adminer;
	}
	location /adminer {
		fastcgi_pass adminer:9000; # service name in the docker network + exposed port
		include fastcgi_params;

		fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
		fastcgi_param SCRIPT_NAME /index.php;
	}
}
