# This workflow runs the project's Continuous Integration (CI) pipeline on GitHub Actions.
name: CI
# Triggers:
# - code is pushed to any branch
# - a Pull Request is opened toward 'develop' or 'main'
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - develop
      - main

jobs:
  # UNIT TESTS
  test-unit:
    # Based on 'ubuntu-22.04' to ensures the CI environment is stable and reproducible over time.
    # Note: No need to run 'npx prisma migrate' because unit tests don't use a real database
    # Note: The unit tests coverage threshold is set to 70% in 'package.json' under "coverageThreshold"
    name: Run unit tests
    runs-on: ubuntu-22.04
    # Commands are run inside the api/ directory where the backend code is located
    defaults:
      run:
        working-directory: api
    steps:
      # Checkout the repository code (equivalent to 'git clone' and 'git checkout' inside the temp test container)
      - uses: actions/checkout@v4
      # Setup Node.js version 24.13.0 (same as in Dockerfiles) and caches npm dependencies for speed
      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: "npm"
          cache-dependency-path: api/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Run unit tests
        run: npm run test:cov

  # END-TO-END TESTS
  test-e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:18.1-alpine3.23
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testuser123
          POSTGRES_DB: e2e
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5440:5432

    env:
      DATABASE_URL: postgresql://testuser:testuser123@localhost:5440/e2e?schema=public
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: eu-west-3
      S3_BUCKET: transcendence
      # We use port 9002 to prevent conflicts with port 9000 when using `act` for local tests
      S3_ENDPOINT: http://localhost:9002
      S3_PUBLIC_URL: http://localhost:9002
      NODE_ENV: development

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: "npm"
          cache-dependency-path: api/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Start MinIO
        run: |
          docker run -d --rm \
            --name minio \
            -p 9002:9000 \
            -e MINIO_ROOT_USER=minioadmin \
            -e MINIO_ROOT_PASSWORD=minioadmin123 \
            minio/minio:RELEASE.2025-09-07T16-13-09Z \
            server /data
          sleep 3
      - name: Create MinIO bucket
        run: |
          curl -sSL https://dl.min.io/client/mc/release/linux-amd64/mc -o mc
          chmod +x mc
          ./mc alias set local http://localhost:9002 minioadmin minioadmin123
          ./mc mb local/transcendence
          ./mc anonymous set public local/transcendence
      - name: Apply migrations
        run: npx prisma migrate deploy
      - name: Run e2e tests
        run: npm run test:e2e
